version: "3"
services:
  docker-practice:
    image: gage-conditions
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - /D_DRIVE/APAData/Github/Pipeline/docker-practice:/home/rstudio/docker-practice

