version: "3"
services:
  docker-dev:
    image: my-vizzy-env
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - /D_DRIVE/APAData/Github/Pipeline/docker-practice:/home/rstudio/docker-dev

