version: "3"
services:
  gage-conditions:
    image: gage-conditions
    ports:
      - "8787:8787"
    volumes:
      - "/D_DRIVE/APAData/Github/DS Vizzies/gage-conditions:/home/rstudio/gage-conditions"
